{% set version = "9.0.0" %}
{% set major_version = version.split(".")[0] %}
{% set sha256 = "7ba81eef7c22ca5da688fdf9d88c20934d2d6b40bfe150ffd338900890aa4610" %}
{% set build_number = 2 %}

package:
  name: clang_packages
  version: {{ version }}

source:
  - url: https://releases.llvm.org/{{ version }}/cfe-{{ version }}.src.tar.xz
    sha256: {{ sha256 }}
    patches:
      - patches/0001-Find-conda-gcc-installation.patch
      - patches/0002-Fix-sysroot-detection-for-linux.patch
      - patches/0002-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
      - patches/0003-clang-Fix-normalizeProgramName-s-handling-of-dots-ou.patch
      - patches/0001-Set-VERSION-in-osx-as-well.patch
    folder: .
  - url: https://releases.llvm.org/{{ version }}/clang-tools-extra-{{ version }}.src.tar.xz
    sha256: ea1c86ce352992d7b6f6649bc622f6a2707b9f8b7153e9f9181a35c76aa3ac10
    folder: tools/extra

build:
  number: {{ build_number }}
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
    # Needed to unpack the source tarball
    - m2w64-xz  # [win]
    # "compiling .pyc files" fails without this
    - python >3
    # Building with ninja on windows for parallel builds
    - ninja  # [win]
    - make   # [unix]
  host:
    - libcxx {{cxx_compiler_version}}  # [osx]
    - llvmdev =={{ version }}

test:
  requires:
    - {{ compiler('cxx') }}
    - cmake >=3.4.3
  files:
    - mytest.c
  commands:
    - $PREFIX/bin/clang --version  # [unix]
    - $PREFIX/bin/clang++ --version  # [unix]
    - $PREFIX/bin/clang-check --version  # [unix]

    - $PREFIX/bin/clang -v -c mytest.c      # [unix]
    - "%LIBRARY_BIN%/clang -v -c mytest.c"  # [win]

    - if not exist %LIBRARY_INC%\\clang\\Lex\\Lexer.h exit 1  # [win]
    - test -f $PREFIX/include/clang/Lex/Lexer.h      # [unix]
    - test -f $PREFIX/lib/libclangBasic.a            # [unix]

about: &about
  home: https://clang.llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: The Clang project
  description: |
    The Clang project provides a language front-end and tooling infrastructure
    for languages in the C language family (C, C++, Objective C/C++, OpenCL,
    CUDA, and RenderScript) for the LLVM project.

outputs:
  - name: clangdev
    script: install_clangdev.sh    # [unix]
    script: install_clangdev.bat   # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clangxx", exact=True) }}
        - {{ pin_subpackage("clang-tools", exact=True) }}
        - {{ pin_subpackage("libclang", exact=True) }}
        - libcxx {{cxx_compiler_version}}  # [osx]
        - llvmdev =={{ version }}
      run:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clangxx", exact=True) }}
        - {{ pin_subpackage("clang-tools", exact=True) }}
        - {{ pin_subpackage("libclang", exact=True) }}
        - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
        - llvmdev =={{ version }}
    test:
      commands:
        - test -f "$PREFIX/include/clang/Config/config.h"   # [unix]
        - test -f "$PREFIX/lib/libclangAST.a"               # [unix]
        - if not exist %LIBRARY_INC%\\clang/Config/config.h exit 1   # [win]
        - if not exist %LIBRARY_LIB%\\clangAST.lib exit 1            # [win]
    about:
      <<: *about
      summary: The Clang project's compilers, libraries, development headers, and tooling

  - name: libclang
    script: install_libclang.sh    # [unix]
    script: install_libclang.bat   # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - libcxx {{cxx_compiler_version}}  # [osx]
        - llvmdev =={{ version }}
        - llvm =={{ version }}
        - {{ pin_subpackage("clang", exact=True) }}
      run:
        - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
    test:
      commands:
        - test -f "$PREFIX/lib/libclang.so"                     # [linux]
        - test -f "$PREFIX/lib/libclang.so.{{major_version}}"   # [linux]
        - test -f "$PREFIX/lib/libclang.dylib"                  # [osx]
        - if not exist %LIBRARY_BIN%\\libclang.dll exit 1       # [win]
    about:
      <<: *about
      summary: C Interface to Clang
      description: |
        Runtime dependencies for libclang, the C Interface to Clang.  It
        provides an API that exposes facilities for parsing source code into an
        abstract syntax tree (AST), loading already-parsed ASTs, traversing the
        AST, associating physical source locations with elements within the
        AST, and other facilities that support Clang-based development tools.
      doc_url: https://clang.llvm.org/doxygen/group__CINDEX.html

  - name: clang
    script: install_clang.sh       # [unix]
    script: install_clang.bat      # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - libcxx                   # [osx]
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - libcxx {{cxx_compiler_version}}  # [osx]
        - llvmdev =={{ version }}
        - llvm =={{ version }}
      run:
        - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
      run_constrained:
        - clangdev {{ version }}
        - clangxx {{ version }}
        - clang-tools {{ version }}
    test:
      commands:
        - clang --version
        - clang-cl --version
        - clang-cpp --version
        - clang-{{major_version}} --version   # [unix]
        - test -f "$PREFIX/lib/libclang-cpp.so"                     # [linux]
        - test -f "$PREFIX/lib/libclang-cpp.so.{{major_version}}"   # [linux]
        - test -f "$PREFIX/lib/libclang-cpp.dylib"                  # [osx]
        - test -f "$PREFIX/lib/clang/{{ version }}/include/stdatomic.h"                    # [unix]
        - if not exist %LIBRARY_LIB%\\clang\\{{ version }}\\include\\stdatomic.h exit 1    # [win]
    about:
      <<: *about
      summary: The Clang compiler for the C language family
      description: |
        Clang is a language front-end for languages in the C language family
        (C, C++, Objective C/C++, OpenCL, CUDA, and RenderScript) for the LLVM
        project. Both a GCC-compatible compiler driver (clang) and an
        MSVC-compatible compiler driver (clang-cl.exe) are provided.

  - name: clangxx
    script: install_clangxx.sh       # [unix]
    script: install_clangxx.bat      # [win]
    requirements:
      host:
        - {{ pin_subpackage("clang", exact=True) }}
      run:
        - {{ pin_subpackage("clang", exact=True) }}
    test:
      commands:
        - clang++ --version
    about:
      <<: *about
      summary: The clang++ compiler from Clang
      description: |
        This is just a symlink to clang which can compile C++. It's provided
        for symmetry with the packages from defaults.

  - name: clang-tools
    script: install_clang_tools.sh    # [unix]
    script: install_clang_tools.bat   # [win]
    requirements:
      build:
        # "compiling .pyc files" fails without this
        - python >3
        - {{ compiler('cxx') }}
        - cmake >=3.4.3
        - ninja  # [win]
        - make   # [unix]
      host:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clangxx", exact=True) }}
        - {{ pin_subpackage("libclang", exact=True) }}
        - libcxx {{cxx_compiler_version}}  # [osx]
        - llvmdev =={{ version }}
        - llvm =={{ version }}
      run:
        - {{ pin_subpackage("clang", exact=True) }}
        - {{ pin_subpackage("clangxx", exact=True) }}
        - {{ pin_compatible("libcxx", max_pin=None) }}  # [osx]
      run_constrained:
        - clangdev {{ version }}
    test:
      commands:
        - clang-check --version
        - clang-tidy --version
    about:
      <<: *about
      summary: Tooling for languages in the C language family
      description: |
        Development tools from the Clang project such as clang-tidy and
        clang-check.
      doc_url: https://clang.llvm.org/docs/ClangTools.html

  - name: python-clang
    build:
      noarch: python
      # Building this output using this recipe is only supported on unix
      # It can still be installed on Windows as it is marked as `noarch: python`
      skip: true  # [win]
    script: build_python_bindings.sh
    requirements:
      host:
        - python
      run:
        - python
        - libclang =={{version}}
    test:
      requires:
        - nose
      source_files:
        - bindings/python/tests
        - bindings/python/examples/cindex
      imports:
        - clang
        - clang.cindex
      commands:
        - cd bindings/python
        - cp tests/cindex/util.py tests
        - nosetests -v
    about:
      <<: *about
      summary: Clang Python bindings

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - jakirkham
    - mattwala
    - SylvainCorlay
    - saraedum
