azure:
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\Miniforge
      SET_PAGEFILE: 'True'
bot:
  abi_migration_branches:
  - 18.x
  - 17.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
# label/llvm_rc would overrule our default compiler stack on osx due to
# strict channel priority; disable for rc-phase; don't commit to main!
channel_priority: flexible
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  win: azure
test: native_and_emulated
