azure:
  settings_win:
    pool:
      vmImage: windows-2019
provider:
  win: azure
conda_forge_output_validation: true
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  osx_arm64: osx_64
test_on_native_only: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
