provider:
  win: azure
conda_forge_output_validation: true
build_platform:
  linux_ppc64le: linux_64
  linux_aarch64: linux_64
  osx_arm64: osx_64
test_on_native_only: true
azure:
  store_build_artifacts: true
conda_build:
  pkg_format: '2'
