matrix:
  # - [[CLANG_VARIANT, 'cling']]
- [[CLANG_VARIANT, default]]
- [[CLANG_VARIANT, flang]]
travis:
  secure:
    BINSTAR_TOKEN: Cvy73xZCRtBPYsQQt4QNndJsfYStcAdtozQM5Dm1YK9WXetQTeVGtG1NXBd7LmX7ktmanj0zERpRq4EPuwUiGWtj+X9XqKvLDPddpS/jpGslOjv/DOzhZemvBGeI6XYgDfEZ1w4mbDjmx1w5P8QVT7CTPAOtjRRSJtkviT8FpmhR0twshq5Zk92pmAprl7hX9Zqgr4VFNbudI1m+/7dGkOjpp9N1R6gw+mcLWqmge2V1ygFe7EdK7lbtMTqmFv/O0pyrADuKtZgA8QADq3Tecjrl/juFEW8fsbqgetGEUOF05PbTCyCavPwgPcNt/9aod7+dvlLp5eRi0dVqTJP/Ioj1DWjHGXU3sXoVaJeKARNdlbVm+M+h159wKgBsrA6latZF25n/7iEi1M53BnaaQwGC7k97a2CJ6JOEiwo84dMF7zoXGEWGIprzGS3DTzBEJA19DGN2tENe8tJRh8SOP6ML8eOwnx7/Y/phccxH9722zHw6Y8rzFPv44EKg7AjTBOIVHsNZNnrnFF+hOVyEzSnSbqfaoH8tYBLUr5/HWU+Xukv//s6Ndcm1kfXyu471QP8s+JIe8bll87CY6nXo9n3k2JFlCpkZSr3w9TjYvktfo70b9gOieiwHdiSdnN34SaEAMhfkM5f8sbQO4AeAPRBGbM16HVRoiW0aB0oGpuI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
