version: 2

jobs:
  build__CLANG_VARIANT_default__CONDA_PY_36:
    working_directory: ~/test
    machine: true
    environment:
      - CLANG_VARIANT: "default"
      - CONDA_PY: "36"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - run:
          name: Print conda-build environment variables
          command: |
            echo "CLANG_VARIANT=${CLANG_VARIANT}"
            echo "CONDA_PY=${CONDA_PY}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build__CLANG_VARIANT_default__CONDA_PY_36
